# Generated by Django 5.2.17 on 2026-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_complete',
            field=models.TextField(blank=True, null=True),
        ),
    ]
